<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerM0CckKR\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerM0CckKR/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerM0CckKR.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerM0CckKR\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerM0CckKR\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'M0CckKR',
    'container.build_id' => '3935d8ef',
    'container.build_time' => 1613639738,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerM0CckKR');
